// Test user data for development
export const TEST_USERS = [
  {
    fullName: "Jane Doe",
    username: "Jane Doe",
    password: "12",
    profile: {
      firstName: "Jane",
      lastName: "Doe",
      username: "Jane Doe",
      city: "New York City",
      state: "New York",
      zip: "11222",
      age: "22",
      company: "Intel",
      title: "Intern Software Engineer",
      startDate: "19/5/2022",
      endDate: "16/8/2022",
      university: "New York University",
      major: "Software Engineering",
      eduStartDate: "19/8/2019",
      eduEndDate: "14/5/2023",
      country: "Greece",
      visaType: "F-1",
      seekingWorkAuth: true,
      aboutMe: "Hi, I'm Jane! I love hiking and exploring outdoor adventures.",
      projects: [],
      certifications: [],
      profilePictureName: null
    }
  },
  {
    fullName: "John Paul",
    username: "John Paul",
    password: "34",
    profile: {
      firstName: "John",
      lastName: "Paul",
      username: "John Paul",
      city: "Jersey City",
      state: "New Jersey",
      zip: "07097",
      age: "24",
      company: "La Pasta",
      title: "Server",
      startDate: "10/4/2017",
      endDate: "15/5/2019",
      university: "Rutgers University",
      major: "Culinary",
      eduStartDate: "16/1/2015",
      eduEndDate: "19/12/2019",
      country: "Brazil",
      visaType: "F-1",
      seekingWorkAuth: true,
      aboutMe: "Hello, I am John and I enjoy cooking.",
      projects: [],
      certifications: [],
      profilePictureName: null
    }
  },
  {
    fullName: "Alice Land",
    username: "Alice Land",
    password: "56",
    profile: {
      firstName: "Alice",
      lastName: "Land",
      username: "Alice Land",
      city: "Lihue",
      state: "Hawaii",
      zip: "96753",
      age: "29",
      company: "Kaua'i Community College",
      title: "Student Researcher",
      startDate: "5/7/2022",
      endDate: "15/9/2024",
      university: "Kaua'i Community College",
      major: "Marine Biology",
      eduStartDate: "17/5/2020",
      eduEndDate: "12/5/2022",
      country: "New Zealand",
      visaType: "F-1",
      seekingWorkAuth: true,
      aboutMe: "I am Alice and I am a student researching marine biology.",
      projects: [],
      certifications: [],
      profilePictureName: null
    }
  },
  {
    fullName: "Bob Stark",
    username: "Bob Stark",
    password: "78",
    profile: {
      firstName: "Bob",
      lastName: "Stark",
      username: "Bob Stark",
      city: "Dallas",
      state: "Texas",
      zip: "75021",
      age: "21",
      company: "",
      title: "",
      startDate: "",
      endDate: "",
      university: "University of Texas at Dallas",
      major: "Engineering",
      eduStartDate: "8/8/2022",
      eduEndDate: "19/5/2026",
      country: "Italy",
      visaType: "M-1",
      seekingWorkAuth: false,
      aboutMe: "Hi, I am Bob. I love gaming and tech reviews.",
      projects: [],
      certifications: [],
      profilePictureName: null
    }
  },
  {
    fullName: "Charlie Brown",
    username: "Charlie Brown",
    password: "90",
    profile: {
      firstName: "Charlie",
      lastName: "Brown",
      username: "Charlie Brown",
      city: "San Jose",
      state: "California",
      zip: "95155",
      age: "26",
      company: "",
      title: "",
      startDate: "",
      endDate: "",
      university: "University of San Jose",
      major: "Information Technology",
      eduStartDate: "15/1/2016",
      eduEndDate: "19/5/2021",
      country: "Canada",
      visaType: "M-1",
      seekingWorkAuth: false,
      aboutMe: "Charlie here! I repair computers and gadgets.",
      projects: [],
      certifications: [],
      profilePictureName: null
    }
  }
];
